#!/bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5

bspc rule -a pavucontrol floating=on
bspc rule -a ristretto floating=on


#############################
# autostart applications
#############################
i3status -c ~/.config/i3status/dzen.config | dzen2 -h 20 -fn 'Droid Sans Mono'
xss-lock -- ~/.bin/i3lock.sh
xautolock -locker 'systemctl suspend' -time 15

