directory: ~/Music
library: ~/Music/library.blb

original_date: yes

match:
    preferred:
        countries: ['US', 'GB|UK']
        media: ['CD', 'Vinyl']
        original_year: yes

import:
    move: yes

plugins: fromfilename bpm lastgenre mpdstats scrub edit fetchart embedart duplicates replaygain

lastgenre:
    auto: yes
    force: yes
    canonical: yes
    min_weight: 30

mpdstats:
    host: localhost
    port: 6600
    rating: yes

fetchart:
    cautious: true

embedart:
    auto: yes
    compare_theshold: 60

duplicates:
    album: yes
    merge: yes

replaygain:
    auto: no
    backend: gstreamer

